---
title: "Clinical Pathology Daily Repo Automated Updates"
output: html_document
date: "2023-08-31"
---

## Global options
```{r Global options}
knitr::opts_chunk$set(echo = FALSE, error = TRUE, warning = FALSE, message = FALSE)
```

## Load libraries
```{r Load libraries and clear environment}

# Load packages ---------------
library(timeDate)
library(readxl)
library(bizdays)
library(dplyr)
library(lubridate)
library(reshape2)
library(knitr)
# library(gdtools)
# library(kableExtra)
library(kableExtra,  "~/R/x86_64-pc-linux-gnu-library/4.2")
library(formattable)
library(rmarkdown)
library(stringr)
library(writexl)
library(gsubfn)
library(tidyr)
library(here)
library(odbc)
library(dbplyr)
library(DBI)
library(glue)
library(foreach)
library(doParallel)
library(parallel)

#Clear existing history
rm(list = ls())
```

## Reference data
```{r Define user path and database schema}
user_directory <- "/Pathology"

oao_cloud_db <- "OAO Cloud DB Kate"
```

## Reference data
```{r Connect to OAO Cloud database and import reference data.}
# CP Reference Tables -------------------
## Begin connection -------
oao_personal_conn <- dbConnect(odbc(), oao_cloud_db)

## MSHS Sites -----------
cp_mshs_sites <- tbl(oao_personal_conn, "CP_SITE_NAMES") %>%
  collect() %>%
  rename(Site = SITE)

## Test Codes -----------

cp_scc_test_codes <- tbl(oao_personal_conn, "CP_SCC_TEST_CODES") %>%
  collect()

cp_sun_test_codes <- tbl(oao_personal_conn, "CP_SUN_TEST_CODES") %>%
  collect()

## TAT Targets ---------
cp_tat_targets <- tbl(oao_personal_conn, "CP_TAT_TARGETS") %>%
  collect() %>%
  mutate(Concate = ifelse(
    PRIORITY == "All" & PT_SETTING == "All", paste(TEST, DIVISION),
    ifelse(PRIORITY != "All" & PT_SETTING == "All",
           paste(TEST, DIVISION, PRIORITY),
           paste(TEST, DIVISION, PRIORITY, PT_SETTING))))

## Patient Setting and ICU -----------
cp_scc_setting <- tbl(oao_personal_conn, "CP_SCC_CLINIC_TYPE") %>%
  collect()

cp_sun_setting <- tbl(oao_personal_conn, "CP_SUN_LOC_TYPE") %>%
  collect()

cp_scc_icu <- tbl(oao_personal_conn, "CP_SCC_ICU") %>%
  collect() %>%
  mutate(SiteCodeName = paste(SITE, WARD, WARD_NAME))

cp_sun_icu <- tbl(oao_personal_conn, "CP_SUN_ICU") %>%
  collect() %>%
  mutate(SiteCodeName = paste(SITE, LOC_CODE, LOC_NAME))

## Disconnect -----------
dbDisconnect(oao_personal_conn)
```

## 60 days data
```{r Connect to database repository tables and find missing dates and files}
# Raw Data 60 Days ---------
## Query raw data repo -------

today <- Sys.Date()

last_60_days <- data.frame(DATE = 
                         seq.Date(from = today - 60, to = today - 1, by = 1)
)

## Table names -----------
daily_summary_temp_table <- "CP_DAILY_REPO_TEMP"
daily_summary_repo_table <- "CP_DAILY_REPO"

count_rows_query <- glue(
  "SELECT COUNT(*) AS NUM_ROWS FROM {daily_summary_repo_table};")

# remove_dates_query <- glue(
#   "DELETE FROM {raw_data_repo_table} where
#   (RESULT_DATE > (TO_DATE('{today}', 'YYYY-MM-DD') - 4));")

oao_personal_conn <- dbConnect(odbc(), oao_cloud_db)

# Remove data more than 60 days ago from repository
dbBegin(oao_personal_conn)

current_num_rows <- dbGetQuery(oao_personal_conn, count_rows_query)$NUM_ROWS

scc_repo_dates <-tbl(oao_personal_conn, daily_summary_repo_table) %>%
  filter(SITE %in% c("MSQ", "MSH")) %>%
  select(RESULT_DATE) %>%
  distinct() %>%
  collect() %>%
  mutate(RESULT_DATE = as.Date(RESULT_DATE)) %>%
  arrange(RESULT_DATE)

sun_repo_dates <-tbl(oao_personal_conn, daily_summary_repo_table) %>%
  filter(!(SITE %in% c("MSQ", "MSH"))) %>%
  select(RESULT_DATE) %>%
  distinct() %>%
  collect() %>%
  mutate(RESULT_DATE = as.Date(RESULT_DATE)) %>%
  arrange(RESULT_DATE)

dbDisconnect(oao_personal_conn)

scc_folder <- paste0(user_directory,
                        "/SCC CP Reports")

scc_missing_data <- last_60_days %>%
  mutate(MissingInDB = !(DATE %in% scc_repo_dates$RESULT_DATE)) %>%
  filter(MissingInDB) %>%
  select(DATE) %>%
  mutate(REPORT_DATE = DATE + 1)

if (nrow(scc_missing_data) > 0){
  missing_scc_files <- list.files(scc_folder,
                                  pattern = paste0(
                                    "^(Doc).+(",
                                    paste0(scc_missing_data$REPORT_DATE, collapse = "|"),
                                    ").xlsx$"))
} else {
  missing_scc_files <- NULL
}

sun_folder <- paste0(user_directory, "/SUN CP Reports")

sun_missing_data <- last_60_days %>%
  mutate(MissingInDB = !(DATE %in% sun_repo_dates$RESULT_DATE)) %>%
  filter(MissingInDB) %>%
  select(DATE) %>%
  mutate(REPORT_DATE = DATE + 1)

if (nrow(sun_missing_data) > 0) {
  missing_sun_files <- list.files(sun_folder,
                                  pattern = paste0(
                                    "^(KPI_Daily_TAT_Report_Updated )",
                                    paste0(sun_missing_data$REPORT_DATE, collapse = "|"),
                                    ".xls$"))
} else {
  missing_sun_files <- NULL
}

if (length(missing_scc_files) > 0) {
  scc_raw_reports <- lapply(
    missing_scc_files, function(x) read_excel(
      path = paste0(scc_folder, "/", x)
    )
  )
} else {
  scc_raw_reports <- NULL
  print("No new SCC reports found.")
}

if (length(missing_sun_files) > 0) {
  sun_raw_reports <- lapply(
    missing_sun_files, function(x) 
      read_excel(
        path = paste0(sun_folder, "/", x),
        col_types = c("text", "text", "text", "text", "text",
                      "text", "text", "text", "text",
                      "numeric", "numeric", "numeric", "numeric", "numeric",
                      "text", "text", "text", "text", "text",
                      "text", "text", "text", "text", "text",
                      "text", "text", "text", "text", "text",
                      "text", "text", "text", "text", "text", "text")
      )
  )
} else {
  sun_raw_reports <- NULL
  print("No new Sunquest reports found.")
}
```

## SCC and Sunquest preprocessing functions
```{r Custom function for preprocessing SCC reports}
source("SCC_Sunquest_Preprocessing_Functions.R")
```

## Summarize preprocessed data for daily repo
```{r Custom function for summarizing preprocessed data}
# Summarize data for each day
cp_daily_summary <- function(x) {
  
  x <- x %>%
    group_by(SITE,
             RESULT_DATE,
             TEST,
             DIVISION,
             SETTING_ROLL_UP,
             DETAILED_SETTING,
             DASHBOARD_SETTING,
             ADJ_PRIORITY,
             DASHBOARD_PRIORITY,
             RECEIVE_RESULT_TARGET,
             COLLECT_RESULT_TARGET) %>%
    summarize(
      # Calculate total number of labs resulted
      TOTAL_RESULTED = n(),
      # Calculate number of labs with valid receive times and collection times
      RECEIVE_TIME_VOL_INCL = sum(RECEIVE_TIME_TAT_INCL, na.rm = TRUE),
      COLLECT_TIME_VOL_INCL = sum(COLLECT_TIME_TAT_INCL, na.rm = TRUE),
      # Calculate number of labs within target TAT
      TOTAL_RECEIVE_RESULT_IN_TARGET =
        sum(RECEIVE_RESULT_IN_TARGET[RECEIVE_TIME_TAT_INCL], na.rm = TRUE),
      TOTAL_COLLECT_RESULT_IN_TARGET =
        sum(COLLECT_RESULT_IN_TARGET[COLLECT_TIME_TAT_INCL], na.rm = TRUE),
      TOTAL_ADD_ON_ORDER = sum(ADD_ON_FINAL %in% c("AddOn"), na.rm = TRUE),
      TOTAL_MISSING_COLLECTIONS = sum(MISSING_COLLECT),
      # Calculate key statistics for collect-to-receive TAT
      COLLECT_RECEIVE_AVG = mean(COLLECT_TO_RECEIVE_TAT[COLLECT_TIME_TAT_INCL],
                                na.rm = TRUE),
      COLLECT_RECEIVE_MEDIAN = median(COLLECT_TO_RECEIVE_TAT[COLLECT_TIME_TAT_INCL],
                                     na.rm = TRUE),
      COLLECT_RECEIVE_95 = quantile(COLLECT_TO_RECEIVE_TAT[COLLECT_TIME_TAT_INCL],
                                   probs = c(0.95), na.rm = TRUE),
      # Calculate key statistics for receive-to-result TAT
      RECEIVE_RESULT_AVG = mean(RECEIVE_TO_RESULT_TAT[RECEIVE_TIME_TAT_INCL],
                               na.rm = TRUE),
      RECEIVE_RESULT_MEDIAN = median(RECEIVE_TO_RESULT_TAT[RECEIVE_TIME_TAT_INCL],
                                    na.rm = TRUE),
      RECEIVE_RESULT_95 = quantile(RECEIVE_TO_RESULT_TAT[RECEIVE_TIME_TAT_INCL],
                                  probs = c(0.95), na.rm = TRUE),
      # Calculate key statistics for collect-to-result TAT
      COLLECT_RESULT_AVG = mean(COLLECT_TO_RESULT_TAT[COLLECT_TIME_TAT_INCL],
                               na.rm = TRUE),
      COLLECT_RESULT_MEDIAN = median(COLLECT_TO_RESULT_TAT[COLLECT_TIME_TAT_INCL],
                                    na.rm = TRUE),
      COLLECT_RESULT_95 = quantile(COLLECT_TO_RESULT_TAT[COLLECT_TIME_TAT_INCL],
                                  probs = c(0.95), na.rm = TRUE),
      .groups = "keep") %>%
    ungroup()
  
  return(x)
}

```

```{r Process SCC and Sunquest reports}

# Process missing SCC and Sunquest files found on shared drive ------
scc_daily_summary <- lapply(
  lapply(X = scc_raw_reports, FUN = preprocess_scc),
  FUN = cp_daily_summary)

if(length(scc_daily_summary) > 0) {
  names(scc_daily_summary) <- paste0("SCC_File_",
                                       c(1:length(scc_daily_summary)))
  
  # Count rows to be added
  new_scc_rows <- sum(sapply(X = scc_daily_summary,
                             FUN = nrow), na.rm = TRUE)
} else {
  new_scc_rows <- 0
}

sun_daily_summary <- lapply(
  lapply(X = sun_raw_reports, FUN = preprocess_sun),
  FUN = cp_daily_summary)

if(length(sun_daily_summary) > 0) {
  names(sun_daily_summary) <- paste0("Sunquest_File_",
                                       c(1:length(sun_daily_summary)))
  
  # Count rows to be added
  new_sun_rows <- sum(sapply(X = sun_daily_summary,
                           FUN = nrow), na.rm = TRUE)
} else {
  new_sun_rows <- 0
}

# Expected number of rows in database table
expected_rows <- current_num_rows + new_scc_rows + new_sun_rows
```

## Database queries
```{r Database writing queries and functions}
# Database writing functions ---------------

## Get values function -----------------
get_values_daily_summary <- function(x, table_name){

  site <- x[1]
  result_date <- x[2]
  test <- x[3]
  division <- x[4]
  setting_roll_up <- x[5]
  detailed_setting <- x[6]
  dashboard_setting <- x[7]
  adj_priority <- x[8]
  dashboard_priority <- x[9]
  receive_result_target <- x[10]
  collect_result_target <- x[11]
  total_resulted <- x[12]
  receive_time_vol_incl <- x[13]
  collect_time_vol_incl <- x[14]
  total_receive_result_in_target <- x[15]
  total_collect_result_in_target <- x[16]
  total_add_on <- x[17]
  total_missing_collections <- x[18]
  collect_receive_avg <- x[19]
  collect_receive_median <- x[20]
  collect_receive_95 <- x[21]
  receive_result_avg <- x[22]
  receive_result_median <- x[23]
  receive_result_95 <- x[24]
  collect_result_avg <- x[25]
  collect_result_median <- x[26]
  collect_result_95 <- x[27]

  values <- glue(
    "INTO \"{table_name}\"
    (SITE,
    RESULT_DATE,
    TEST,
    DIVISION,
    SETTING_ROLL_UP,
    DETAILED_SETTING,
    DASHBOARD_SETTING,
    ADJ_PRIORITY,
    DASHBOARD_PRIORITY,
    RECEIVE_RESULT_TARGET,
    COLLECT_RESULT_TARGET,
    TOTAL_RESULTED,
    RECEIVE_TIME_VOL_INCL,
    COLLECT_TIME_VOL_INCL,
    TOTAL_RECEIVE_RESULT_IN_TARGET,
    TOTAL_COLLECT_RESULT_IN_TARGET,
    TOTAL_ADD_ON_ORDER,
    TOTAL_MISSING_COLLECTIONS,
    COLLECT_RECEIVE_AVG,
    COLLECT_RECEIVE_MEDIAN,
    COLLECT_RECEIVE_95,
    RECEIVE_RESULT_AVG,
    RECEIVE_RESULT_MEDIAN,
    RECEIVE_RESULT_95,
    COLLECT_RESULT_AVG,
    COLLECT_RESULT_MEDIAN,
    COLLECT_RESULT_95)

    VALUES (
    '{site}',
    TO_DATE('{result_date}', 'YYYY-MM-DD'),
    '{test}',
    '{division}',
    '{setting_roll_up}',
    '{detailed_setting}',
    '{dashboard_setting}',
    '{adj_priority}',
    '{dashboard_priority}',
    '{receive_result_target}',
    '{collect_result_target}',
    '{total_resulted}',
    '{receive_time_vol_incl}',
    '{collect_time_vol_incl}',
    '{total_receive_result_in_target}',
    '{total_collect_result_in_target}',
    '{total_add_on}',
    '{total_missing_collections}',
    '{collect_receive_avg}',
    '{collect_receive_median}',
    '{collect_receive_95}',
    '{receive_result_avg}',
    '{receive_result_median}',
    '{receive_result_95}',
    '{collect_result_avg}',
    '{collect_result_median}',
    '{collect_result_95}')"
    )

  return(values)
}

## Insert all into temporary table ---------
all_data_glue <- function(x) {
  all_data <- glue('INSERT ALL
                   {x}
                   SELECT 1 from DUAL;')
}

## Merge into repository table --------
merge_to_daily_repo_query <- function(temp_table, repo_table) {
  
  query <- glue('MERGE INTO "{daily_summary_repo_table}" RT
                    USING "{daily_summary_temp_table}" SOURCE_TABLE
                    ON (RT."SITE" = SOURCE_TABLE."SITE" AND
                        RT."RESULT_DATE" = SOURCE_TABLE."RESULT_DATE" AND
                        RT."TEST" = SOURCE_TABLE."TEST" AND
                        RT."DETAILED_SETTING" = SOURCE_TABLE."DETAILED_SETTING" AND
                        RT."ADJ_PRIORITY" = SOURCE_TABLE."ADJ_PRIORITY")
                    WHEN MATCHED THEN
                    UPDATE SET RT."DIVISION" = SOURCE_TABLE."DIVISION",
                               RT."SETTING_ROLL_UP" = SOURCE_TABLE."SETTING_ROLL_UP",
                               RT."DASHBOARD_SETTING" = SOURCE_TABLE."DASHBOARD_SETTING",
                               RT."DASHBOARD_PRIORITY" = SOURCE_TABLE."DASHBOARD_PRIORITY",
                               RT."RECEIVE_RESULT_TARGET" = SOURCE_TABLE."RECEIVE_RESULT_TARGET",
                               RT."COLLECT_RESULT_TARGET" = SOURCE_TABLE."COLLECT_RESULT_TARGET",
                               RT."TOTAL_RESULTED" = SOURCE_TABLE."TOTAL_RESULTED",
                               RT."RECEIVE_TIME_VOL_INCL" = SOURCE_TABLE."RECEIVE_TIME_VOL_INCL",
                               RT."COLLECT_TIME_VOL_INCL" = SOURCE_TABLE."COLLECT_TIME_VOL_INCL",
                               RT."TOTAL_RECEIVE_RESULT_IN_TARGET" = SOURCE_TABLE."TOTAL_RECEIVE_RESULT_IN_TARGET",
                               RT."TOTAL_COLLECT_RESULT_IN_TARGET" = SOURCE_TABLE."TOTAL_COLLECT_RESULT_IN_TARGET",
                               RT."TOTAL_ADD_ON_ORDER" = SOURCE_TABLE."TOTAL_ADD_ON_ORDER",
                               RT."TOTAL_MISSING_COLLECTIONS" = SOURCE_TABLE."TOTAL_MISSING_COLLECTIONS",
                               RT."COLLECT_RECEIVE_AVG" = SOURCE_TABLE."COLLECT_RECEIVE_AVG",
                               RT."COLLECT_RECEIVE_MEDIAN" = SOURCE_TABLE."COLLECT_RECEIVE_MEDIAN",
                               RT."COLLECT_RECEIVE_95" = SOURCE_TABLE."COLLECT_RECEIVE_95",
                               RT."RECEIVE_RESULT_AVG" = SOURCE_TABLE."RECEIVE_RESULT_AVG",
                               RT."RECEIVE_RESULT_MEDIAN" = SOURCE_TABLE."RECEIVE_RESULT_MEDIAN",
                               RT."RECEIVE_RESULT_95" = SOURCE_TABLE."RECEIVE_RESULT_95",
                               RT."COLLECT_RESULT_AVG" = SOURCE_TABLE."COLLECT_RESULT_AVG",
                               RT."COLLECT_RESULT_MEDIAN" = SOURCE_TABLE."COLLECT_RESULT_MEDIAN",
                               RT."COLLECT_RESULT_95" = SOURCE_TABLE."COLLECT_RESULT_95"
                    WHEN NOT MATCHED THEN
                    INSERT(RT."SITE",
                           RT."RESULT_DATE",
                           RT."TEST",
                           RT."DIVISION",
                           RT."SETTING_ROLL_UP",
                           RT."DETAILED_SETTING",
                           RT."DASHBOARD_SETTING",
                           RT."ADJ_PRIORITY",
                           RT."DASHBOARD_PRIORITY",
                           RT."RECEIVE_RESULT_TARGET",
                           RT."COLLECT_RESULT_TARGET",
                           RT."TOTAL_RESULTED",
                           RT."RECEIVE_TIME_VOL_INCL",
                           RT."COLLECT_TIME_VOL_INCL",
                           RT."TOTAL_RECEIVE_RESULT_IN_TARGET",
                           RT."TOTAL_COLLECT_RESULT_IN_TARGET",
                           RT."TOTAL_ADD_ON_ORDER",
                           RT."TOTAL_MISSING_COLLECTIONS",
                           RT."COLLECT_RECEIVE_AVG",
                           RT."COLLECT_RECEIVE_MEDIAN",
                           RT."COLLECT_RECEIVE_95",
                           RT."RECEIVE_RESULT_AVG",
                           RT."RECEIVE_RESULT_MEDIAN",
                           RT."RECEIVE_RESULT_95",
                           RT."COLLECT_RESULT_AVG",
                           RT."COLLECT_RESULT_MEDIAN",
                           RT."COLLECT_RESULT_95"
                    )
                    VALUES(SOURCE_TABLE."SITE",
                           SOURCE_TABLE."RESULT_DATE",
                           SOURCE_TABLE."TEST",
                           SOURCE_TABLE."DIVISION",
                           SOURCE_TABLE."SETTING_ROLL_UP",
                           SOURCE_TABLE."DETAILED_SETTING",
                           SOURCE_TABLE."DASHBOARD_SETTING",
                           SOURCE_TABLE."ADJ_PRIORITY",
                           SOURCE_TABLE."DASHBOARD_PRIORITY",
                           SOURCE_TABLE."RECEIVE_RESULT_TARGET",
                           SOURCE_TABLE."COLLECT_RESULT_TARGET",
                           SOURCE_TABLE."TOTAL_RESULTED",
                           SOURCE_TABLE."RECEIVE_TIME_VOL_INCL",
                           SOURCE_TABLE."COLLECT_TIME_VOL_INCL",
                           SOURCE_TABLE."TOTAL_RECEIVE_RESULT_IN_TARGET",
                           SOURCE_TABLE."TOTAL_COLLECT_RESULT_IN_TARGET",
                           SOURCE_TABLE."TOTAL_ADD_ON_ORDER",
                           SOURCE_TABLE."TOTAL_MISSING_COLLECTIONS",
                           SOURCE_TABLE."COLLECT_RECEIVE_AVG",
                           SOURCE_TABLE."COLLECT_RECEIVE_MEDIAN",
                           SOURCE_TABLE."COLLECT_RECEIVE_95",
                           SOURCE_TABLE."RECEIVE_RESULT_AVG",
                           SOURCE_TABLE."RECEIVE_RESULT_MEDIAN",
                           SOURCE_TABLE."RECEIVE_RESULT_95",
                           SOURCE_TABLE."COLLECT_RESULT_AVG",
                           SOURCE_TABLE."COLLECT_RESULT_MEDIAN",
                           SOURCE_TABLE."COLLECT_RESULT_95"
                    );')
  
  return(query)
}
  
# Glue query for truncating temporary table
truncate_query <- glue('TRUNCATE TABLE "{daily_summary_temp_table}";')

```

## Add SCC data to OAO database tables
```{r Add new SCC data to database table}
system.time(
  scc_status_table <- if(length(scc_daily_summary) > 0) {
    print("Begin adding SCC data to daily summary repository.")
    
    lapply(
      X = seq_along(scc_daily_summary),
      
      FUN = function(n) {
        temp_table <- daily_summary_temp_table
        repo_table <- daily_summary_repo_table
        
        scc_status_table <- NULL
        
        scc_daily_repo <- scc_daily_summary[[n]] %>%
          mutate(SITE = as.character(SITE),
                 RESULT_DATE = format(RESULT_DATE, "%Y-%m-%d"),
                 TEST = as.character(TEST),
                 DIVISION = as.character(DIVISION),
                 SETTING_ROLL_UP = as.character(SETTING_ROLL_UP),
                 DETAILED_SETTING = as.character(DETAILED_SETTING),
                 DASHBOARD_SETTING = as.character(DASHBOARD_SETTING),
                 ADJ_PRIORITY = as.character(ADJ_PRIORITY),
                 DASHBOARD_PRIORITY = as.character(DASHBOARD_PRIORITY),
                 RECEIVE_RESULT_TARGET = as.integer(RECEIVE_RESULT_TARGET),
                 COLLECT_RESULT_TARGET = as.integer(COLLECT_RESULT_TARGET),
                 TOTAL_RESULTED = as.integer(TOTAL_RESULTED),
                 RECEIVE_TIME_VOL_INCL = as.integer(RECEIVE_TIME_VOL_INCL),
                 COLLECT_TIME_VOL_INCL = as.integer(COLLECT_TIME_VOL_INCL),
                 TOTAL_RECEIVE_RESULT_IN_TARGET =
                   as.integer(TOTAL_RECEIVE_RESULT_IN_TARGET),
                 TOTAL_COLLECT_RESULT_IN_TARGET =
                   as.integer(TOTAL_COLLECT_RESULT_IN_TARGET),
                 TOTAL_ADD_ON_ORDER = as.integer(TOTAL_ADD_ON_ORDER),
                 TOTAL_MISSING_COLLECTIONS =
                   as.integer(TOTAL_MISSING_COLLECTIONS),
                 COLLECT_RECEIVE_AVG = round(as.numeric(COLLECT_RECEIVE_AVG),
                                             digits = 6),
                 COLLECT_RECEIVE_MEDIAN = round(as.numeric(COLLECT_RECEIVE_MEDIAN),
                                                digits = 6),
                 COLLECT_RECEIVE_95 = round(as.numeric(COLLECT_RECEIVE_95),
                                            digits = 6),
                 RECEIVE_RESULT_AVG = round(as.numeric(RECEIVE_RESULT_AVG),
                                            digits = 6),
                 RECEIVE_RESULT_MEDIAN = round(as.numeric(RECEIVE_RESULT_MEDIAN),
                                               digits = 6),
                 RECEIVE_RESULT_95 = round(as.numeric(RECEIVE_RESULT_95),
                                           digits = 6),
                 COLLECT_RESULT_AVG = round(as.numeric(COLLECT_RESULT_AVG),
                                            digits = 6),
                 COLLECT_RESULT_MEDIAN = round(as.numeric(COLLECT_RESULT_MEDIAN),
                                               digits = 6),
                 COLLECT_RESULT_95 = round(as.numeric(COLLECT_RESULT_95),
                                           digits = 6)
                 ) %>%
          mutate(across(where(is.numeric), replace_na, NA)) %>%
          mutate(across(everything(), gsub, pattern = "\'",
                        replacement = "''")) %>%
          mutate(across(everything(), replace_na, '')) %>%
          mutate(across(everything(), gsub, pattern = "&",
                replacement = "'||chr(38)||'"))
        
        inserts <- lapply(
          lapply(
            lapply(split(scc_daily_repo, 1:nrow(scc_daily_repo)),
                   as.list),
            as.character),
          FUN = get_values_daily_summary, daily_summary_temp_table
        )
        
        values <- glue_collapse(inserts, sep = "\n\n")
        
        # # Combine into statements from get_values() function and combine with insert statements
        # all_data <- glue('INSERT ALL {values} SELECT 1 from DUAL;')
        all_data <- all_data_glue(x = values)
        
        merge_query <- merge_to_daily_repo_query(temp_table = daily_summary_temp_table,
                                                 repo_table = daily_summary_repo_table)
        
        # Connect to database
      oao_personal_conn <- dbConnect(odbc(), "OAO Cloud DB Kate")
      dbBegin(oao_personal_conn)
      
      print(paste("Database writing for SCC file", n))
      
      tryCatch({
          print("Before first truncate")
          dbExecute(oao_personal_conn, truncate_query)
          print("After first truncate")
          dbExecute(oao_personal_conn, all_data)
          print("After all rows added to temporary table")
          dbExecute(oao_personal_conn, merge_query)
          print("After merge into repo table")
          dbExecute(oao_personal_conn, truncate_query)
          print("After second truncate")
          dbCommit(oao_personal_conn)
          print("After repo table commit")
          dbDisconnect(oao_personal_conn)
          print(paste0("Success! Scc file ", n, " added to database!"))
          scc_status_table <- rbind(scc_status_table,
                                    paste0("File ", missing_scc_files[n],
                                                    " successfully added to database!"))
        },
        error = function(err){
          # print("error")
          dbRollback(oao_personal_conn)
          dbExecute(oao_personal_conn, truncate_query)
          dbDisconnect(oao_personal_conn)
          print(paste0("Error! Code experienced an error adding SCC File ", n, " to database!"))
          scc_status_table <- rbind(scc_status_table,
                                    paste0("Check ", missing_scc_files[n]))
        }
      )
      }
    )
  } else {
    print("No SCC files to add.")
  }
)

scc_status_table <- unlist(scc_status_table)
```

## Add Sunquest data to OAO database tables
```{r Add new Sunquest data to database table}
system.time(
  sun_status_table <- if(length(sun_daily_summary) > 0) {
    print("Begin adding Sunquest data to daily summary repository.")
    
    lapply(
      X = seq_along(sun_daily_summary),
      
      FUN = function(n) {
        temp_table <- daily_summary_temp_table
        repo_table <- daily_summary_repo_table
        
        sun_status_table <- NULL
        
        sun_daily_repo <- sun_daily_summary[[n]] %>%
          mutate(SITE = as.character(SITE),
                 RESULT_DATE = format(RESULT_DATE, "%Y-%m-%d"),
                 TEST = as.character(TEST),
                 DIVISION = as.character(DIVISION),
                 SETTING_ROLL_UP = as.character(SETTING_ROLL_UP),
                 DETAILED_SETTING = as.character(DETAILED_SETTING),
                 DASHBOARD_SETTING = as.character(DASHBOARD_SETTING),
                 ADJ_PRIORITY = as.character(ADJ_PRIORITY),
                 DASHBOARD_PRIORITY = as.character(DASHBOARD_PRIORITY),
                 RECEIVE_RESULT_TARGET = as.integer(RECEIVE_RESULT_TARGET),
                 COLLECT_RESULT_TARGET = as.integer(COLLECT_RESULT_TARGET),
                 TOTAL_RESULTED = as.integer(TOTAL_RESULTED),
                 RECEIVE_TIME_VOL_INCL = as.integer(RECEIVE_TIME_VOL_INCL),
                 COLLECT_TIME_VOL_INCL = as.integer(COLLECT_TIME_VOL_INCL),
                 TOTAL_RECEIVE_RESULT_IN_TARGET =
                   as.integer(TOTAL_RECEIVE_RESULT_IN_TARGET),
                 TOTAL_COLLECT_RESULT_IN_TARGET =
                   as.integer(TOTAL_COLLECT_RESULT_IN_TARGET),
                 TOTAL_ADD_ON_ORDER = as.integer(TOTAL_ADD_ON_ORDER),
                 TOTAL_MISSING_COLLECTIONS =
                   as.integer(TOTAL_MISSING_COLLECTIONS),
                 COLLECT_RECEIVE_AVG = round(as.numeric(COLLECT_RECEIVE_AVG),
                                             digits = 6),
                 COLLECT_RECEIVE_MEDIAN = round(as.numeric(COLLECT_RECEIVE_MEDIAN),
                                                digits = 6),
                 COLLECT_RECEIVE_95 = round(as.numeric(COLLECT_RECEIVE_95),
                                            digits = 6),
                 RECEIVE_RESULT_AVG = round(as.numeric(RECEIVE_RESULT_AVG),
                                            digits = 6),
                 RECEIVE_RESULT_MEDIAN = round(as.numeric(RECEIVE_RESULT_MEDIAN),
                                               digits = 6),
                 RECEIVE_RESULT_95 = round(as.numeric(RECEIVE_RESULT_95),
                                           digits = 6),
                 COLLECT_RESULT_AVG = round(as.numeric(COLLECT_RESULT_AVG),
                                            digits = 6),
                 COLLECT_RESULT_MEDIAN = round(as.numeric(COLLECT_RESULT_MEDIAN),
                                               digits = 6),
                 COLLECT_RESULT_95 = round(as.numeric(COLLECT_RESULT_95),
                                           digits = 6)
                 ) %>%
          mutate(across(where(is.numeric), replace_na, NA)) %>%
          mutate(across(everything(), gsub, pattern = "\'",
                        replacement = "''")) %>%
          mutate(across(everything(), replace_na, '')) %>%
          mutate(across(everything(), gsub, pattern = "&",
                replacement = "'||chr(38)||'"))
        
        inserts <- lapply(
          lapply(
            lapply(split(sun_daily_repo, 1:nrow(sun_daily_repo)),
                   as.list),
            as.character),
          FUN = get_values_daily_summary, daily_summary_temp_table
        )
        
        values <- glue_collapse(inserts, sep = "\n\n")
        
        # # Combine into statements from get_values() function and combine with insert statements
        # all_data <- glue('INSERT ALL {values} SELECT 1 from DUAL;')
        all_data <- all_data_glue(x = values)
        
        merge_query <- merge_to_daily_repo_query(temp_table = daily_summary_temp_table,
                                                 repo_table = daily_summary_repo_table)
        
        # Connect to database
      oao_personal_conn <- dbConnect(odbc(), "OAO Cloud DB Kate")
      dbBegin(oao_personal_conn)
      
      print(paste("Database writing for Sunquest file", n))
      
      tryCatch({
          print("Before first truncate")
          dbExecute(oao_personal_conn, truncate_query)
          print("After first truncate")
          dbExecute(oao_personal_conn, all_data)
          print("After all rows added to temporary table")
          dbExecute(oao_personal_conn, merge_query)
          print("After merge into repo table")
          dbExecute(oao_personal_conn, truncate_query)
          print("After second truncate")
          dbCommit(oao_personal_conn)
          print("After repo table commit")
          dbDisconnect(oao_personal_conn)
          print(paste0("Success! Scc file ", n, " added to database!"))
          sun_status_table <- rbind(sun_status_table,
                                    paste0("File ", missing_sun_files[n],
                                                    " successfully added to database!"))
        },
        error = function(err){
          # print("error")
          dbRollback(oao_personal_conn)
          dbExecute(oao_personal_conn, truncate_query)
          dbDisconnect(oao_personal_conn)
          print(paste0("Error! Code experienced an error adding Sunquest File ", n, " to database!"))
          sun_status_table <- rbind(sun_status_table,
                                    paste0("Check ", missing_sun_files[n]))
        }
      )
      }
    )
  } else {
    print("No Sunquest files to add.")
  }
)

sun_status_table <- unlist(sun_status_table)
```

```{r Summary output messages}
scc_status_table

sun_status_table

```

## Sanity check for number of rows
```{r Check number of rows after adding new data}

oao_personal_conn <- dbConnect(odbc(), "OAO Cloud DB Kate")
dbBegin(oao_personal_conn)
new_total_rows <- dbGetQuery(oao_personal_conn, count_rows_query)$NUM_ROWS
dbDisconnect(oao_personal_conn)

if(new_total_rows == expected_rows){
  print("Total rows in repo table is equal to expected number of rows.")
} else {
  print("Total number of rows in repo table is not equal to the expected number of rows.")
  print(paste("Current total number of rows:", new_total_rows))
  print(paste("Expected total number of rows:", expected_rows))
}
```