---
title: "CP Weekly Data Migration"
date: "`r format(Sys.Date(), '%m/%d/%y')`"
output: html_document
---

  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```  


```{r Install and load packages, echo = FALSE, warning = FALSE, message = FALSE}
rm(list = ls())

# Load libraries
library(timeDate)
library(readxl)
library(bizdays)
library(dplyr)
library(lubridate)
library(reshape2)
library(knitr)
library(kableExtra)
library(formattable)
library(rmarkdown)
library(stringr)
library(writexl)
library(ggplot2)
library(gridExtra)
library(scales)
library(ggQC)
library(ggplot2)
library(janitor)
library(tidyr)
library(purrr)
library(lubridate)
library(pool)
library(DBI)
library(odbc)
library(dbplyr)
library(glue)
library(assertr)
library(doParallel)
```


```{r global_options, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.align = "center")
```


```{r Clear history and import relevant data}
# Set working directory ------
dsn <- "OAO Cloud DB Production"
dsn_oracle <- paste0(dsn, " Oracle")

conn <- dbConnect(odbc(), dsn)


if ("Presidents" %in% list.files("/SharedDrive/")) {
  user_directory <- paste0("/SharedDrive/deans/Presidents/HSPI-PM/",
                           "Operations Analytics and Optimization/Projects/",
                           "Service Lines/Lab Kpi/Data")
} else {
  user_directory <- paste0("/SharedDrive/deans/Presidents/HSPI-PM/",
                           "Operations Analytics and Optimization/Projects/",
                           "Service Lines/Lab Kpi/Data")
}

user_path <- paste0(user_directory, "\\*.*")


# Import data for two scenarios - first time compiling repo and updating repo ----------
# initial_run <- TRUE



# Import Clinical Pathology analysis reference data ---------------
# reference_file <- paste0(user_directory,
#                          "/Code Reference/",
#                          "Analysis Reference 2023-10-13.xlsx")

scc_test_code <- tbl(conn,"LAB_KPI_SCC_TEST_CODES") %>%
  collect()
sun_test_code <- tbl(conn,"LAB_KPI_SUN_TEST_CODES") %>%
  collect()

todays_date <- as.Date(Sys.Date(), format = "%Y-%m-%d")
yesterday <- todays_date -1
# scc_test_code <- read_excel(reference_file, sheet = "SCC_TestCodes")
# sun_test_code <- read_excel(reference_file, sheet = "SUN_TestCodes")

#Remove Good Friday from MSHS Holidays for Biopsies and Cytology
nyse_holidays <- as.Date(holidayNYSE(year = 1990:2100))
good_friday <- as.Date(GoodFriday())
mshs_holiday <- nyse_holidays[good_friday != nyse_holidays]
#Determine whether yesterday was a holiday/weekend
holiday_det <- isHoliday(as.timeDate(yesterday), holidays = mshs_holiday)

#Set up a calendar for collect to received TAT calculations for Path & Cyto
create.calendar("MSHS_working_days", mshs_holiday,
                weekdays = c("saturday", "sunday"))
bizdays.options$set(default.calendar = "MSHS_working_days")

# Power path patient settings
patient_setting <- tbl(conn,"LAB_KPI_AP_PATIENT_SETTING") %>%
  collect()



# tat_targets <- read_excel(reference_file, sheet = "Turnaround Targets")
tat_targets <- tbl(conn,"LAB_KPI_TURNAROUND_TARGETS") %>%
  collect()

tat_targets <- tat_targets %>%
  mutate(Concate = ifelse(
    PRIORITY == "All" & PT_SETTING == "All", paste(TEST, DIVISION),
    ifelse(PRIORITY != "All" & `PT_SETTING` == "All",
           paste(TEST, DIVISION, PRIORITY),
           paste(TEST, DIVISION, PRIORITY, PT_SETTING))))

scc_icu <- tbl(conn,"LAB_KPI_SCC_ICU") %>%
  collect()
sun_icu <-  tbl(conn,"LAB_KPI_SUN_ICU") %>%
  collect()

scc_icu <- scc_icu %>%
  mutate(SiteCodeName = paste(SITE, WARD, WARD_NAME))

sun_icu <- sun_icu %>%
  mutate(SiteCodeName = paste(SITE, LOC_CODE, LOC_NAME))

scc_setting <- tbl(conn,"LAB_KPI_SCC_CLINICTYPE") %>%
  collect()
sun_setting <- tbl(conn,"LAB_KPI_SUN_LOCTYPE") %>%
  collect()

mshs_site <- tbl(conn,"LAB_KPI_SITE_NAMES") %>%
  collect()

cp_micro_lab_order <- c("Troponin",
                        "Lactate WB",
                        "BUN",
                        "HGB",
                        "PT",
                        "Rapid Flu",
                        "C. diff")

all_sites <- c("MSH", "MSQ", "MSBI", "MSB", "MSW", "MSM", "MSSN", "RTC")
hosp_sites <- c("MSH", "MSQ", "MSBI", "MSB", "MSW", "MSM", "MSSN")
infusion_sites <- c("RTC")

pt_setting_order <- c("ED", "ICU", "IP Non-ICU", "Amb", "Other")
pt_setting_order2 <- c("ED & ICU", "IP Non-ICU", "Amb", "Other")
dashboard_pt_setting <- c("ED & ICU", "IP Non-ICU", "Amb")

dashboard_priority_order <- c("All", "Stat", "Routine")

cp_division_order <- c("Chemistry", "Hematology", "Microbiology RRL", "Infusion")

dbDisconnect(conn)




```

```{r Custom functions for database}
# Function to push data to database ----
get_values_updated <- function(x, columns,table_name){
  
  values <- glue("INTO \"{table_name}\" ({columns}) 
                 VALUES{x}")
  
  return(values)
}

write_temporary_table_to_database_and_merge_updated <- function(data, key_columns, destination_table_name, source_table_name, update_columns) {
  
  
  if(destination_table_name == "LAB_KPI_PREPROCESSED_DAILY"){
    
    
    process_data <- data %>% mutate_if(is.factor, as.character) %>%
    mutate_if(is.character, function(x) gsub("\'", "''", x)) %>%
    mutate_if(is.character, function(x) gsub("&", "' || chr(38) || '", x)) %>%
    mutate_if(is.character, function(x) paste0("'", x, "'")) %>%
    mutate_if(is.Date, function(x) paste0("TO_DATE('", x, "', 'YYYY-MM-DD')")) %>%
    mutate(ORDERTIME = paste0("TO_TIMESTAMP('", ORDERTIME, "', 'YYYY-MM-DD HH24:MI:SS')"),
           COLLECTTIME = paste0("TO_TIMESTAMP('", COLLECTTIME, "', 'YYYY-MM-DD HH24:MI:SS')"),
           RECEIVETIME = paste0("TO_TIMESTAMP('", RECEIVETIME, "', 'YYYY-MM-DD HH24:MI:SS')"),
           RESULTTIME = paste0("TO_TIMESTAMP('", RESULTTIME, "', 'YYYY-MM-DD HH24:MI:SS')")) %>%
    mutate(across(where(is.numeric),~ replace_na(as.character(.x), "''")))

    
  } else{
    
    process_data <- data %>% mutate_if(is.factor, as.character) %>%
    mutate_if(is.character, function(x) gsub("\'", "''", x)) %>%
    mutate_if(is.character, function(x) gsub("&", "' || chr(38) || '", x)) %>%
    mutate_if(is.character, function(x) paste0("'", x, "'")) %>%
    mutate_if(is.Date, function(x) paste0("TO_DATE('", x, "', 'YYYY-MM-DD')")) %>%
    mutate(CASE_CREATED_DATE = paste0("TO_TIMESTAMP('", CASE_CREATED_DATE, "', 'YYYY-MM-DD HH24:MI:SS')"),
           COLLECTION_DATE = paste0("TO_TIMESTAMP('", COLLECTION_DATE, "', 'YYYY-MM-DD HH24:MI:SS')"),
           RECEIVED_DATE = paste0("TO_TIMESTAMP('", RECEIVED_DATE, "', 'YYYY-MM-DD HH24:MI:SS')"),
           SIGNED_OUT_DATE = paste0("TO_TIMESTAMP('", SIGNED_OUT_DATE, "', 'YYYY-MM-DD HH24:MI:SS')")) %>%
    mutate(across(where(is.numeric),~ replace_na(as.character(.x), "''")))

  }
  
  
  columns <- paste(colnames(process_data), collapse = ",")
  
  values <- process_data %>% mutate(values = paste0("(", col_concat(., sep = ","), ")")) %>%
    select(values)
  
  values$values <- gsub('NA', "", values$values)
  
  data_records <- split(values ,1:nrow(values))
  
  
  registerDoParallel()
  inserts <- foreach(record = data_records) %dopar% {
    tmp <- as.list(record)
    tmp <- as.character(tmp)
    tmp <- get_values_updated(tmp,columns = columns, table_name = source_table_name)
  }
  registerDoSEQ()
  
  chunk_length <- 500
  split_queries <- split(inserts, ceiling(seq_along(inserts)/chunk_length))
  
  
  split_queries_sql_statements <- list()
  for (i in 1:length(split_queries)) {
    row <- glue_collapse(split_queries[[i]], sep = "\n\n")
    # row <- gsub('NA', "", row)
    # row <- gsub("&", " ' || chr(38) || ' ", row)
    sql <- glue('INSERT ALL {row} SELECT 1 FROM DUAL;')
    split_queries_sql_statements <- append(split_queries_sql_statements, gsub("\\n", "", sql))
  }
  
  
  
  # glue statement for dropping table
  truncate_query <- glue('TRUNCATE TABLE "{source_table_name}";')
  
  #glue statement to copy empty table
  copy_table_query <- glue('CREATE TABLE {source_table_name}
                      AS
                      SELECT *
                      FROM {destination_table_name} WHERE 1=0;')
  
  #glue statement to drop table
  drop_query <- glue('DROP TABLE {source_table_name};')
  
  
  # Clear the staging data
  tryCatch({
    ch = dbConnect(odbc(), dsn)
    dbBegin(ch)
    if(dbExistsTable(ch,source_table_name)){
      dbExecute(ch,drop_query)
    }
    dbExecute(ch,copy_table_query)
    dbExecute(ch,truncate_query)
    
    dbCommit(ch)
    dbDisconnect(ch)
  },
  error = function(err){
    print(err)
    print("Table Copy Failed")
    dbRollback(ch)
    dbDisconnect(ch)
    
  })
  
  
  registerDoParallel()
  system.time(
    outputPar <- foreach(i = 1:length(split_queries_sql_statements), .packages = c("DBI", "odbc"))%dopar%{
      #Connecting to database through DBI
      ch = dbConnect(odbc(), dsn)
      #Test connection
      tryCatch({
        dbBegin(ch)
        dbExecute(ch, split_queries_sql_statements[[i]])
        dbCommit(ch)
      },
      error = function(err){
        #print("error2")split_queries_sql_statements[[1]]
        dbRollback(ch)
        dbDisconnect(ch)
        print("Staging Data Write Error")
      })
    }
  )
  registerDoSEQ()
  
  
  ###MErge Statement
  # key_columns <- c("FUNCTION", "CATEGORY", "SITE", "CC", "NAME", "EXPTYPE", "SUB_ACCOUNT", "SUB_ACCOUNT_DESCRIPTION", "SUPPLY_MAPPING_FILE_CATEGORY", "MONTH")
  merge_on_cols <- paste(paste0("DT.",key_columns, " = ST.",key_columns), sep="", collapse = ",")
  merge_on_cols <- gsub(',', " AND ", merge_on_cols)
  
  # update_columns <- c("SUM_OF_MONTH_BUDGET", "SUM_OF_MONTH_ACTUAL", "SUM_OF_YTD_BUDGET", "SUM_OF_YTD_ACTUAL", "SUM_OF_ANNUAL_BUDGET")
  update_on_cols <- paste(paste0("DT.",update_columns, " = ST.",update_columns), sep="", collapse = ",")
  
  
  get_dest_table_cols <-  paste(paste0("DT.",unique(c(key_columns,update_columns))), sep="", collapse = ",")
  get_source_table_values <- paste(paste0("ST.",unique(c(key_columns,update_columns))), sep="", collapse = ",")
  
  # destination_table_name <- "BSC_FINANCE_TABLE"
  # source_table_name <- "BSC_FINANCE_TABLE_TESTING"
  
  merge_query <- glue("MERGE INTO \"{destination_table_name}\" DT 
                        USING \"{source_table_name}\" ST 
                        ON ({merge_on_cols})
                      WHEN MATCHED THEN UPDATE SET
                      {update_on_cols}
                      WHEN NOT MATCHED THEN
                      INSERT ({get_dest_table_cols})
                      VALUES({get_source_table_values})
                      ")
  
  
  ch = dbConnect(odbc(), dsn_oracle)
  #Test connection
  tryCatch({
    dbBegin(ch)
    dbExecute(ch, merge_query)
    dbExecute(ch,drop_query)
    dbCommit(ch)
    dbDisconnect(ch)
    # print("success")
    print("Merge Succesfull")
    
  },
  error = function(err){
    #print("error")
    dbRollback(ch)
    dbDisconnect(ch)
    print("Merge Failed")
    
  })
  
}


```

```{r Custom function for SUNQUEST processing}
# Function to process SUNQUEST data ----
preprocess_daily_sun <- function(raw_sun) {
  
  # Remove any duplicates
  raw_sun <- unique(raw_sun)
  # Correct and format any timestamps that were not imported correctly
  raw_sun[c("OrderDateTime",
            "CollectDateTime",
            "ReceiveDateTime",
            "ResultDateTime")] <-
    lapply(raw_sun[c("OrderDateTime",
                     "CollectDateTime",
                     "ReceiveDateTime",
                     "ResultDateTime")],
           function(x) ifelse(!is.na(x) & str_detect(x, "\\*.*\\*")  == TRUE,
                              str_replace(x, "\\*.*\\*", ""), x))
  
  raw_sun <- raw_sun %>%
    mutate(across(where(is.character), gsub,
                  pattern = "\\*.*\\*",
                  replacement = ""))
  
  raw_sun[c("OrderDateTime",
            "CollectDateTime",
            "ReceiveDateTime",
            "ResultDateTime")] <-
    lapply(raw_sun[c("OrderDateTime",
                     "CollectDateTime",
                     "ReceiveDateTime",
                     "ResultDateTime")],
           as.POSIXct, tz = "UTC", format = "%m/%d/%Y %H:%M:%S")
  
  # Sunquest lookup references
  # Crosswalk labs included and remove out of scope labs
  raw_sun <- left_join(raw_sun, sun_test_code,
                       by = c("TestCode" = "SUN_TEST_CODE"))
  
  # Determine if test is included based on crosswalk results
  raw_sun <- raw_sun %>%
    mutate(TestIncl = !is.na(TEST)) %>%
    filter(TestIncl)
  
  
  # Crosswalk unit type
  raw_sun <- left_join(raw_sun, sun_setting,
                       by = c("LocType" = "LOC_TYPE"))
  
  # Crosswalk site name
  raw_sun <- left_join(raw_sun, mshs_site,
                       by = c("HospCode" = "DATA_SITE"))
  
  # # Sunquest data formatting-----------------------------
  # Preprocess Sunquest data and add any necessary columns
  raw_sun <- raw_sun %>%
    mutate(
      # Determine if unit is an ICU based on site mappings
      ICU = paste(SITE, LocCode, LocName) %in% sun_icu$SiteCodeName,
      # Create a column for resulted date
      ResultedDate = as.Date(ResultDateTime, format = "%m/%d/%Y"),
      # Create master setting column to identify ICU and IP Non-ICU units
      MasterSetting = ifelse(SETTING_ROLL_UP == "IP" & ICU, "ICU",
                             ifelse(SETTING_ROLL_UP == "IP" & !ICU,
                                    "IP Non-ICU", SETTING_ROLL_UP)),
      # Create dashboard setting column to roll up master settings based on
      # desired dashboard grouping(ie, group ED and ICU together)
      DashboardSetting = ifelse(MasterSetting %in% c("ED", "ICU"), "ED & ICU",
                                MasterSetting),
      #
      # Create column with adjusted priority based on operational assumption
      # that all ED and ICU labs are treated as stat
      AdjPriority = ifelse(MasterSetting %in% c("ED", "ICU") |
                             SpecimenPriority %in% "S", "Stat", "Routine"),
      #
      # Calculate turnaround times
      CollectToReceive =
        as.numeric(ReceiveDateTime - CollectDateTime, units = "mins"),
      ReceiveToResult =
        as.numeric(ResultDateTime - ReceiveDateTime, units = "mins"),
      CollectToResult =
        as.numeric(ResultDateTime - CollectDateTime, units = "mins"),
      #
      # Determine if order was an add on or original order based on time between
      # order and receive times
      AddOnMaster = ifelse(as.numeric(OrderDateTime - ReceiveDateTime,
                                      units = "mins") > 5, "AddOn", "Original"),
      #
      # Determine if collection time is missing
      MissingCollect = ifelse(CollectDateTime == OrderDateTime, 1, 0),
      #
      # Determine TAT target based on test, priority, and patient setting
      # Create column concatenating test and division to determine TAT targets
      Concate1 = paste(TEST, DIVISION),
      #
      # Create dashboard priority column
      DashboardPriority = ifelse(
        tat_targets$PRIORITY[match(
          Concate1,
          paste(tat_targets$TEST, tat_targets$DIVISION))] == "All",
        "All", AdjPriority),
      # Create column concatenating test, division, and priority to determine
      # TAT targets
      Concate2 = paste(TEST, DIVISION, DashboardPriority),
      # Create column concatenating test, division, priority, and setting to
      # determine TAT targets
      Concate3 = paste(TEST, DIVISION, DashboardPriority, MasterSetting),
      #
      # Determine Receive to Result TAT target using this logic:
      # 1. Try to match test, priority, and setting (applicable for labs with
      # different TAT targets based on patient setting and order priority)
      # 2. Try to match test and priority (applicable for labs with different
      # TAT targets based on order priority)
      # 3. Try to match test - this is for tests with (applicable for labs with
      # TAT targets that are independent of patient setting or priority)
      #
      # Determine Receive to Result TAT target based on above logic/scenarios
      ReceiveResultTarget =
        # Match on scenario 1
        ifelse(!is.na(match(Concate3, tat_targets$Concate)),
               tat_targets$RECEIVE_TO_RESULT_TARGET[
                 match(Concate3, tat_targets$Concate)],
               # Match on scenario 2
               ifelse(!is.na(match(Concate2, tat_targets$Concate)),
                      tat_targets$RECEIVE_TO_RESULT_TARGET[
                        match(Concate2, tat_targets$Concate)],
                      # Match on scenario 3
                      tat_targets$RECEIVE_TO_RESULT_TARGET[
                        match(Concate1, tat_targets$Concate)])),
      #
      # Determine Collect to Result TAT target based on above logic/scenarios
      CollectResultTarget =
        # Match on scenario 1
        ifelse(!is.na(match(Concate3, tat_targets$Concate)),
               tat_targets$COLLECT_TO_RESULT_TARGET[
                 match(Concate3, tat_targets$Concate)],
               # Match on scenario 2
               ifelse(!is.na(match(Concate2, tat_targets$Concate)),
                      tat_targets$COLLECT_TO_RESULT_TARGET[
                        match(Concate2, tat_targets$Concate)],
                      # Match on scenario 3
                      tat_targets$COLLECT_TO_RESULT_TARGET[
                        match(Concate1, tat_targets$Concate)])),
      #
      # Determine if Receive to Result and Collect to Result TAT meet targets
      ReceiveResultInTarget = ifelse(ReceiveToResult <= ReceiveResultTarget, 1, 0),
      CollectResultInTarget = ifelse(CollectToResult <= CollectResultTarget, 1, 0),
      #
      # Create column with patient name, order ID, test, collect, receive, and
      # result date and determine if there is a duplicate; order time excluded
      Concate4 = paste(PtNumber, HISOrderNumber, TSTName,
                       CollectDateTime, ReceiveDateTime, ResultDateTime),
      DuplTest = duplicated(Concate4),
      #
      # Determine whether or not to include this particular lab in TAT analysis
      # Exclusion criteria:
      # 1. Add on orders
      # 2. Orders from "Other" settings
      # 3. Orders with collect or receive times after result time
      # 4. Orders with missing collect, receive, or result timestamps
      # 5. Orders with missing collection times are excluded from
      # collect-to-result and collect-to-receive turnaround time analyis
      ReceiveTime_TATInclude = ifelse(AddOnMaster == "AddOn" |
                                        MasterSetting == "Other" |
                                        CollectToReceive < 0 |
                                        CollectToResult < 0 |
                                        ReceiveToResult < 0 |
                                        is.na(CollectToResult) |
                                        is.na(ReceiveToResult), 0, 1),
      CollectTime_TATInclude = ifelse(MissingCollect == 1 |
                                        AddOnMaster == "AddOn" |
                                        MasterSetting == "Other" |
                                        CollectToReceive < 0 |
                                        CollectToResult < 0 |
                                        ReceiveToResult < 0 |
                                        is.na(CollectToResult) |
                                        is.na(ReceiveToResult), 0, 1))
  
  # Remove duplicate tests
  raw_sun <- raw_sun %>%
    filter(!DuplTest)
  
  # Determine volume of labs associated with each date and identify correct date
  sun_resulted_dates_vol <- raw_sun %>%
    group_by(ResultedDate) %>%
    summarize(VolLabs = n()) %>%
    arrange(desc(VolLabs)) %>%
    ungroup()
  
  sun_correct_date <- sun_resulted_dates_vol$ResultedDate[1]
  
  raw_sun <- raw_sun %>%
    filter(ResultedDate %in% sun_correct_date)%>%
    mutate(ICU = as.character(ICU))
  
  # Select columns
  sun_master <- raw_sun[, c("LocCode", "LocName",
                            "HISOrderNumber", "PhysName",
                            "PtNumber", "SHIFT",
                            "TSTName", "TEST", "DIVISION", "SpecimenPriority",
                            "SITE", "ICU", "LocType",
                            "SETTING", "SETTING_ROLL_UP",
                            "MasterSetting", "DashboardSetting",
                            "AdjPriority", "DashboardPriority",
                            "OrderDateTime", "CollectDateTime",
                            "ReceiveDateTime", "ResultDateTime",
                            "ResultedDate",
                            "CollecttoReceive", "ReceivetoResult",
                            "CollecttoResult",
                            "AddOnMaster", "MissingCollect",
                            "ReceiveResultTarget", "CollectResultTarget",
                            "ReceiveResultInTarget", "CollectResultInTarget",
                            "ReceiveTime_TATInclude", "CollectTime_TATInclude")]
  
  colnames(sun_master) <- c("LocCode", "LocName",
                            "OrderID", "RequestMD",
                            "MSMRN", "WorkShift",
                            "TestName", "Test", "Division", "OrderPriority",
                            "Site", "ICU", "LocType",
                            "Setting", "SettingRollUp",
                            "MasterSetting", "DashboardSetting",
                            "AdjPriority", "DashboardPriority",
                            "OrderTime", "CollectTime",
                            "ReceiveTime", "ResultTime",
                            "ResultDate",
                            "CollectToReceiveTAT", "ReceiveToResultTAT",
                            "CollectToResultTAT",
                            "AddOnMaster", "MissingCollect",
                            "ReceiveResultTarget", "CollectResultTarget",
                            "ReceiveResultInTarget", "CollectResultInTarget",
                            "ReceiveTime_TATInclude", "CollectTime_TATInclude")
  
  colnames(sun_master) <- toupper(colnames(sun_master))
  
  sun_master <-  sun_master %>%
    mutate(
      # Find month name from result date
      YEAR = year(RESULTDATE),
      MONTHNO = month(RESULTDATE),
      MONTHNAME = month(RESULTDATE, label = TRUE, abbr = TRUE),
      MONTHROLLUP = as.Date(paste0(MONTHNO, "/",
                                   1, "/",
                                   YEAR),
                            format = "%m/%d/%Y"),
      # WeekNo = format(ResultDate, "%U"),
      WEEKSTART = RESULTDATE - (wday(RESULTDATE) - 1),
      WEEKEND = RESULTDATE + (7 - wday(RESULTDATE)),
      WEEKOF = paste0(format(WEEKSTART, "%m/%d/%y"),
                      "-",
                      format(WEEKEND, "%m/%d/%y")))
  
  sun_master <- sun_master %>%
    drop_na(c(ORDERID, TEST,RESULTTIME)) %>%
    distinct()
  
}


```

```{r Custom function for SCC processing}
# Function to process SCC data ----
preprocess_scc <- function(raw_scc)  {
  # Preprocess SCC data -------------------------------
  # Remove any duplicates
  raw_scc <- unique(raw_scc)
  
  # Correct and format any timestamps that were not imported correctly
  raw_scc[c("ORDERING_DATE",
            "COLLECTION_DATE",
            "RECEIVE_DATE",
            "VERIFIED_DATE")] <-
    lapply(raw_scc[c("ORDERING_DATE",
                     "COLLECTION_DATE",
                     "RECEIVE_DATE",
                     "VERIFIED_DATE")],
           function(x)
             ifelse(!is.na(x) & str_detect(x, "\\*.*\\*"),
                    str_replace(x, "\\*.*\\*", ""), x))
  
  raw_scc <- raw_scc %>%
    mutate(across(where(is.character), gsub,
                  pattern = "\\*.*\\*",
                  replacement = ""))
  
  raw_scc[c("ORDERING_DATE",
            "COLLECTION_DATE",
            "RECEIVE_DATE",
            "VERIFIED_DATE")] <-
    lapply(raw_scc[c("ORDERING_DATE",
                     "COLLECTION_DATE",
                     "RECEIVE_DATE",
                     "VERIFIED_DATE")],
           as.POSIXct, tz = "UTC",
           format = "%Y-%m-%d %H:%M:%OS",
           options(digits.sec = 1))
  
  # SCC lookup references ----------------------------------------------
  # Crosswalk in scope labs
  raw_scc <- left_join(raw_scc,
                       scc_test_code,
                       by = c("TEST_ID" = "SCC_TEST_ID"))
  
  # Determine if test is included based on crosswalk results
  raw_scc <- raw_scc %>%
    mutate(TestIncl = !is.na(TEST)) %>%
    filter(TestIncl)
  
  # Crosswalk unit type
  raw_scc <- left_join(raw_scc, scc_setting,
                       by = c("CLINIC_TYPE" = "CLINIC_TYPE"))
  # Crosswalk site name
  raw_scc <- raw_scc %>%
    mutate(COLLECT_CENTER_ID = str_sub(COLLECT_CENTER_ID, 1, 1))
  
  raw_scc <- left_join(raw_scc, mshs_site,
                       by = c("COLLECT_CENTER_ID" = "DATA_SITE"))
  
  raw_scc <- raw_scc%>%
    select(-SITE.x) %>%
    rename(SITE = SITE.y)
  
  # Preprocess SCC data and add any necessary columns
  raw_scc <- raw_scc %>%
    mutate(
      # Subset HGB and BUN tests completed at RTC as a separate site since they
      # are processed at RTC
      SITE = ifelse(TEST %in% c("HGB", "BUN") &
                      str_detect(replace_na(WARD_NAME, ""),
                                 "Ruttenberg Treatment Center"),
                    "RTC", SITE),
      # Update division to Infusion for RTC
      DIVISION = ifelse(SITE %in% c("RTC"), "Infusion", DIVISION),
      # Determine if unit is an ICU based on site mappings
      ICU = paste(SITE, Ward, WARD_NAME) %in% scc_icu$SiteCodeName,
      # Create a column for resulted date
      ResultedDate = date(VERIFIED_DATE),
      # Create master setting column to identify ICU and IP Non-ICU units
      MasterSetting = ifelse(SETTING_ROLL_UP == "IP" & ICU, "ICU",
                             ifelse(SETTING_ROLL_UP == "IP" & !ICU,
                                    "IP Non-ICU", SETTING_ROLL_UP)),
      # Create dashboard setting column to roll up master settings based on
      # desired dashboard grouping (ie, group ED and ICU together)
      DashboardSetting = ifelse(MasterSetting %in% c("ED", "ICU"),
                                "ED & ICU", MasterSetting),
      # Create column with adjusted priority based on assumption that all ED and
      # ICU labs are treated as stat per operational leadership
      AdjPriority = ifelse(MasterSetting %in% c("ED", "ICU") |
                             PRIORITY %in% "S", "Stat", "Routine"),
      # Calculate turnaround times
      CollectToReceive =
        as.numeric(RECEIVE_DATE - COLLECTION_DATE, units = "mins"),
      ReceiveToResult =
        as.numeric(VERIFIED_DATE - RECEIVE_DATE, units = "mins"),
      CollectToResult =
        as.numeric(VERIFIED_DATE - COLLECTION_DATE, units = "mins"),
      #
      # Determine if order was an add on or original order based on time between
      # order and receive times
      AddOnMaster = ifelse(as.numeric(ORDERING_DATE - RECEIVE_DATE,
                                      units = "mins")
                           > 5, "AddOn", "Original"),
      # Determine if collection time is missing
      MissingCollect = ifelse(CollectToReceive == 0,1,0),
      #
      # Determine TAT based on test, division, priority, and patient setting
      # Create column concatenating test and division to determine TAT targets
      Concate1 = paste(TEST, DIVISION),
      #
      # Create dashboard priority column
      DashboardPriority = ifelse(
        tat_targets$PRIORITY[match(
          Concate1, 
          paste(tat_targets$TEST, tat_targets$DIVISION))] == "All",
        "All", AdjPriority),
      # Create column concatenating test, division, and priority to determine
      # TAT targets
      Concate2 = paste(TEST, DIVISION, DashboardPriority),
      # Create column concatenating test, division, priority, and setting to
      # determine TAT targets
      Concate3 = paste(TEST, DIVISION, DashboardPriority, MasterSetting),
      #
      # Determine Receive to Result TAT target using this logic:
      # 1. Try to match test, division, priority, and setting (applicable for
      # labs with different TAT targets based on patient setting and order priority)
      # 2. Try to match test, division, and priority (applicable for labs with
      # different TAT targets based on order priority)
      # 3. Try to match test and division - (applicable for labs with
      # TAT targets that are independent of patient setting or priority)
      #
      # Determine Receive to Result TAT target based on above logic/scenarios
      ReceiveResultTarget =
        # Match on scenario 1
        ifelse(!is.na(match(Concate3, tat_targets$Concate)),
               tat_targets$RECEIVE_TO_RESULT_TARGET[
                 match(Concate3, tat_targets$Concate)],
               # Match on scenario 2
               ifelse(!is.na(match(Concate2, tat_targets$Concate)),
                      tat_targets$RECEIVE_TO_RESULT_TARGET[
                        match(Concate2, tat_targets$Concate)],
                      # Match on scenario 3
                      tat_targets$RECEIVE_TO_RESULT_TARGET[
                        match(Concate1, tat_targets$Concate)])),
      #
      # Determine Collect to Result TAT target based on above logic/scenarios
      CollectResultTarget =
        # Match on scenario 1
        ifelse(!is.na(match(Concate3, tat_targets$Concate)),
               tat_targets$COLLECT_TO_RESULT_TARGET[
                 match(Concate3, tat_targets$Concate)],
               # Match on scenario 2
               ifelse(!is.na(match(Concate2, tat_targets$Concate)),
                      tat_targets$COLLECT_TO_RESULT_TARGET[
                        match(Concate2, tat_targets$Concate)],
                      # Match on scenario 3
                      tat_targets$COLLECT_TO_RESULT_TARGET[
                        match(Concate1, tat_targets$Concate)])),
      #
      # Determine if Receive to Result and Collect to Result TAT meet targets
      ReceiveResultInTarget = ifelse(ReceiveToResult <= ReceiveResultTarget, 1,0),
      CollectResultInTarget = ifelse(CollectToResult <= CollectResultTarget, 1,0),
      # Create column with patient name, order ID, test, collect, receive, and
      # result date and determine if there is a duplicate; order time excluded
      Concate4 = paste(LAST_NAME, FIRST_NAME,
                       ORDER_ID, TEST_NAME,
                       COLLECTION_DATE, RECEIVE_DATE, VERIFIED_DATE),
      DuplTest = duplicated(Concate4),
      # Determine whether or not to include this particular lab in TAT analysis
      # Exclusion criteria:
      # 1. Add on orders
      # 2. Orders from "Other" settings
      # 3. Orders with collect or receive times after result time
      # 4. Orders with missing collect, receive, or result timestamps
      # 5. Orders with missing collection times are excluded from
      # collect-to-result and collect-to-receive turnaround time analyis
      ReceiveTime_TATInclude = ifelse(AddOnMaster == "AddOn" |
                                        MasterSetting == "Other" |
                                        CollectToReceive < 0 |
                                        CollectToResult < 0 |
                                        ReceiveToResult < 0 |
                                        is.na(CollectToResult) |
                                        is.na(ReceiveToResult), 0, 1),
      CollectTime_TATInclude = ifelse(MissingCollect == 1 |
                                        AddOnMaster == "AddOn" |
                                        MasterSetting == "Other" |
                                        CollectToReceive < 0 |
                                        CollectToResult < 0 |
                                        ReceiveToResult < 0 |
                                        is.na(CollectToResult) |
                                        is.na(ReceiveToResult), 0, 1))
  
  # Remove duplicate tests
  raw_scc <- raw_scc %>%
    filter(!DuplTest)
  
  # Determine volume of labs associated with each date and identify correct date
  scc_resulted_dates_vol <- raw_scc %>%
    group_by(ResultedDate) %>%
    summarize(VolLabs = n()) %>%
    arrange(desc(VolLabs)) %>%
    ungroup()
  
  scc_correct_date <- scc_resulted_dates_vol$ResultedDate[1]
  
  raw_scc <- raw_scc %>%
    filter(ResultedDate %in% scc_correct_date) %>%
    mutate(ICU = as.character(ICU))
  
  # Select columns
  scc_master <- raw_scc[, c("Ward", "WARD_NAME",
                            "ORDER_ID", "REQUESTING_DOC NAME",
                            "MPI", "WORK SHIFT",
                            "TEST_NAME", "TEST", "DIVISION", "PRIORITY",
                            "SITE", "ICU", "CLINIC_TYPE",
                            "SETTING", "SETTING_ROLL_UP",
                            "MasterSetting", "DashboardSetting",
                            "AdjPriority", "DashboardPriority",
                            "ORDERING_DATE", "COLLECTION_DATE",
                            "RECEIVE_DATE", "VERIFIED_DATE",
                            "ResultedDate",
                            "CollectToReceive", "ReceiveToResult",
                            "CollectToResult",
                            "AddOnMaster", "MissingCollect",
                            "ReceiveResultTarget", "CollectResultTarget",
                            "ReceiveResultInTarget", "CollectResultInTarget",
                            "ReceiveTime_TATInclude",
                            "CollectTime_TATInclude")]
  # Rename columns
  colnames(scc_master) <- c("LocCode", "LocName",
                            "OrderID", "RequestMD",
                            "MSMRN", "WorkShift",
                            "TestName", "Test", "Division", "OrderPriority",
                            "Site", "ICU", "LocType",
                            "Setting", "SettingRollUp",
                            "MasterSetting", "DashboardSetting",
                            "AdjPriority", "DashboardPriority",
                            "OrderTime", "CollectTime",
                            "ReceiveTime", "ResultTime",
                            "ResultDate",
                            "CollectToReceiveTAT", "ReceiveToResultTAT",
                            "CollectToResultTAT",
                            "AddOnMaster", "MissingCollect",
                            "ReceiveResultTarget", "CollectResultTarget",
                            "ReceiveResultInTarget", "CollectResultInTarget",
                            "ReceiveTime_TATInclude", "CollectTime_TATInclude")
  
  colnames(scc_master) <- toupper(colnames(scc_master))
  
  scc_master <- scc_master %>%
    mutate(
      # Find month name from result date
      YEAR = year(RESULTDATE),
      MONTHNO = month(RESULTDATE),
      MONTHNAME = month(RESULTDATE, label = TRUE, abbr = TRUE),
      MONTHROLLUP = as.Date(paste0(MONTHNO, "/",
                                   1, "/",
                                   YEAR),
                            format = "%m/%d/%Y"),
      # WeekNo = format(ResultDate, "%U"),
      WEEKSTART = RESULTDATE - (wday(RESULTDATE) - 1),
      WEEKEND = RESULTDATE + (7 - wday(RESULTDATE)),
      WEEKOF = paste0(format(WEEKSTART, "%m/%d/%y"),
                      "-",
                      format(WEEKEND, "%m/%d/%y")))
  
  scc_master <- scc_master %>%
    drop_na(c(ORDERID, TEST,RESULTTIME,TESTNAME)) %>%
    distinct()
  
}

```

```{r Powerpath data processing}

# Copied from Automated Daily Dashboard/AP_functions_data_preprocessing.R
site_mapping <- function(data){
  
  
  data <- data %>%
    mutate(Facility = case_when(Facility == "KH" ~ "MSB",
                                Facility == "R" ~ "MSW",
                                Facility == "STL" ~ "MSM",
                                Facility == "BIMC" ~ "MSBI",
                                Facility == "SNCH" ~ "MSSN",
                                Facility == "MSS" ~ "MSH",
                                Facility == "SL" ~ "MSM",
                                Facility == "PACC" ~ "MSUS",
                                TRUE ~ Facility ))
  
  
  
}


format_dates <- function(data){
  
  data[c("Case_created_date",
                 "Collection_Date",
                 "Received_Date",
                 "signed_out_date")] <-
    lapply(data[c("Case_created_date",
                          "Collection_Date",
                          "Received_Date",
                          "signed_out_date")],
           as.POSIXct, tz = "", format = "%m/%d/%y %I:%M %p" ,origin = "1970-01-01")
  
  data
  
}


# Function to preprate prepare cytology data for pre-processing by crosswalking
# Epic and PowerPath data
# combines orginal cyto_prep, pre_processing_pp in Daily_Run_AP_Custom_Functions

cyto_prep <- function(pp_data) {
  if (is.null(pp_data) ||  nrow(pp_data) == 0) {
    summarized_table <- NULL
    return(summarized_table)
  } else {
    
    pp_data <- pp_data %>%
      mutate(Case_no =  str_replace_all(Case_no,"\\*failed to decode utf16\\*",""))
      

    # Subset PowerPath data to keep Cyto Gyn and Cyto NonGyn and primary
    # specimens only
    cyto_data <- pp_data %>%
      filter(spec_group %in% c("CYTO NONGYN","CYTO GYN","BREAST"),
             spec_sort_order == 'A')
    
    cyto_data <- cyto_data %>%
      mutate(TEST_NAME =  case_when(Spec_code == 'BREA1' & spec_group == 'BREAST' ~ 'Breast Biopsy',
                                    spec_group == 'CYTO NONGYN' ~ 'Cytology NONGYN',
                                    spec_group == 'CYTO GYN' ~ 'Cytology GYN',
                                    TRUE ~ 'Breast Large/Resection'))

    
    # cyto_data <- merge(x = cyto_data, y = epic_data_specimens,
    #                     by.x = "Case_no",
    #                     by.y = "SPECIMEN_ID")
    
    
    
    # Crosswalk Rev_ctr and patient setting for PowerPath data
    cyto_data <- left_join(cyto_data,
                           patient_setting,
                           by = c('Rev_ctr' = 'REV_CTR'))
    
    # update sites/facilities
    cyto_data <- site_mapping(cyto_data)
    
    # Update MSB patient setting based on patient type column
    cyto_data <- cyto_data %>%
      mutate(PATIENT_SETTING = case_when(Rev_ctr == "MSBK" & (patient_type == "A" | patient_type == "O") ~ "Amb",
                                         Rev_ctr == "MSBK" &  patient_type == "IN" ~ "IP",
                                         TRUE ~ PATIENT_SETTING))
    
    # Crosswalk TAT targets based on spec_group and patient setting
    # cyto_data <- left_join(cyto_data,
    #                        tat_targets_ap,
    #                        by = c('spec_group' = 'SPEC_GROUP', 'PATIENT_SETTING' = 'PATIENT_SETTING'))

    #Change all Dates into POSIXct format to start the calculations
    cyto_data <- format_dates(cyto_data)
    
    # Add columns for turnaround time calculations:
    # Collection to signed out (in calendar days) and
    # received to signed out (in business days)
    cyto_data <- cyto_data %>%
      mutate(
        # Add column for collected to signed out turnaround time in calendar days
        Collection_to_signed_out =
          as.numeric(difftime(signed_out_date,Collection_Date,units="days")),
        # Add column for received to signed out turnaround time in business days
        Received_to_signed_out = bizdays(Received_Date, signed_out_date),
        # Prepare data for accessioned volume analysis
        # First find the date of the last weekday and add 1 for report date
        report_date_only = as.Date(signed_out_date) + 1,
        MONTH_ROLLUP = floor_date(signed_out_date, "month"),
        #  Find the accessioned date and use this for determining accessioned volume
        acc_date_only = as.Date(Received_Date),
        TAT_TARGET =  case_when(TEST_NAME == 'Breast Biopsy' ~ 3,
                                TEST_NAME == 'Breast Large/Resection' ~ 5,
                                TEST_NAME == 'Cytology GYN' ~ 8,
                                TRUE ~ 8),
        IS_TAT_WITHIN_TARGET =  if_else(Received_to_signed_out <= TAT_TARGET,1,0)) 
    
    cyto_data <- cyto_data %>%
      select(Facility,
             Priority,
             Spec_code,
             Specimen_description,
             CPT_code,
             Rev_ctr,
             Encounter_no,
             MRN,
             Case_no,
             Case_created_date,
             Collection_Date,
             Received_Date,
             signed_out_date,
             Refmd_code,
             spec_sort_order,
             TEST_NAME,
             PATIENT_SETTING,
             Collection_to_signed_out,
             Received_to_signed_out,
             TAT_TARGET,
             IS_TAT_WITHIN_TARGET,
             spec_group,
             Refmd_name)
    names(cyto_data) <- toupper(names(cyto_data))
    

    #summarize the data to be used for analysis and to be stored as historical
    #repo
    # summarized_table <- cyto_data %>%
    #   group_by(Spec_code,
    #            spec_group,
    #            Facility,
    #            Patient.Setting,
    #            Rev_ctr,
    #            as.Date(signed_out_date),
    #            weekdays(as.Date(signed_out_date)),
    #            Received.to.signed.out.target..Days.,
    #            Collected.to.signed.out.target..Days.,
    #            acc_date_only,
    #            weekdays(acc_date_only),
    #            report_date_only,
    #            weekdays(report_date_only)) %>%
    #   summarise(no_cases_signed = n(),
    #             lab_metric_tat_avg = round(mean(Received_to_signed_out,
    #                                             na.rm = TRUE), 0),
    #             lab_metric_tat_med = round(median(Received_to_signed_out,
    #                                               na.rm = TRUE), 0),
    #             lab_metric_tat_sd = round(sd(Received_to_signed_out, na.rm = TRUE), 1),
    #             lab_metric_within_target = as.numeric(format(
    #               round(
    #                 sum(Received_to_signed_out <= Received.to.signed.out.target..Days.,
    #                     na.rm = TRUE) / sum(
    #                       Received_to_signed_out >= 0, na.rm = TRUE), 2))),
    #             patient_metric_tat_avg = as.numeric(format(
    #               ceiling(mean(Collection_to_signed_out, na.rm = TRUE)))),
    #             patient_metric_tat_med = round(median(Collection_to_signed_out,
    #                                                   na.rm = TRUE), 0),
    #             patient_metric_tat_sd = round(sd(Collection_to_signed_out,
    #                                              na.rm = TRUE), 1),
    #             cyto_acc_vol = as.numeric(sum((report_date_only - 1) == acc_date_only,
    #                                           na.rm = TRUE)))
    
    
    
    return(cyto_data)
  }
}

```


```{r Extract Files}
# Get Max Date from Database ----
todays_date <- as.Date(Sys.Date(), format = "%Y-%m-%d")
dsn <- "OAO Cloud DB Production"
conn <- dbConnect(odbc(), dsn)
get_max_date_scc <- glue("SELECT TO_CHAR(MAX(RESULTDATE),'YYYY-MM-DD') AS MAXDATE
                          FROM LAB_KPI_PREPROCESSED_DAILY
                          WHERE SITE IN ('MSH','MSQ','MSUS','MSC');")

get_max_date_sun <- glue("SELECT TO_CHAR(MAX(RESULTDATE),'YYYY-MM-DD') AS MAXDATE
                          FROM LAB_KPI_PREPROCESSED_DAILY
                          WHERE SITE IN ('MSSN','MSBI','MSM','MSW');")

get_max_date_pp <- glue("SELECT TO_CHAR(MAX(SIGNED_OUT_DATE),'YYYY-MM-DD') AS MAXDATE
                          FROM LAB_KPI_POWERPATH_CYTO_BIOPSY;")

max_date_scc <- dbGetQuery(conn,
                           get_max_date_scc)
max_date_scc <- max_date_scc$MAXDATE[[1]]

# max_date_scc < - as.Date(max_date_scc, format = "%Y-%m-%d") 
  

max_date_sun <- dbGetQuery(conn,
                           get_max_date_sun)
max_date_sun <- max_date_sun$MAXDATE[[1]]

# max_date_sun < - as.Date(max_date_sun)

max_date_pp <- dbGetQuery(conn,
                           get_max_date_pp)
max_date_pp <- max_date_pp$MAXDATE[[1]]

dbDisconnect(conn)


if(as.Date(max_date_scc)+2 >= todays_date){
  
  file_list_scc_flag <- FALSE
  
}else{
  
  # Compute dates to add to database based on Max dates ----
  scc_date_range <- seq(from = as.Date(max_date_scc)+2,
                        to = todays_date,
                        by = "day")

  # Extract SCC pattern and files ----
  pattern_scc = paste0("^(Doc){1}.+",
                       scc_date_range,
                       ".xlsx",
                       collapse = "|")
  file_list_scc <- list.files(
    path = paste0(user_directory, "/SCC CP Reports"),
    pattern = pattern_scc)

  file_list_scc_flag <- TRUE

}


if(as.Date(max_date_sun)+2 >= todays_date){
  
  file_list_sun_flag <- FALSE
  
}else{
  sun_date_range <- seq(from = as.Date(max_date_sun)+2,
                      to = todays_date,
                      by = "day")


  # Extract SUN pattern and files ----
  pattern_sun <-  paste0("^(KPI_Daily_TAT_Report){1}.*",
                         sun_date_range,
                         ".xls", collapse = "|")
  file_list_sun <- list.files(
    path = paste0(user_directory, "/SUN CP Reports"),
    pattern = pattern_sun)

  file_list_sun_flag <- TRUE

}



if(as.Date(max_date_pp)+2 >= todays_date){
  
  file_list_pp_flag <- FALSE
  
}else{
  
  # Compute dates to add to database based on Max dates ----
  pp_date_range <- seq(from = as.Date(max_date_pp)+2,
                        to = todays_date,
                        by = "day")

  
  

  # Extract pp pattern and files ----
  pattern_kpi = paste0("^(KPI REPORT - RAW DATA V4_V2){1}.*",
                     pp_date_range,
                     ".xls",
                     collapse = "|")
  file_list_pp <- list.files(
    path = paste0(user_directory, "/AP & Cytology Signed Cases Reports"),
    pattern = pattern_kpi)

  file_list_pp_flag <- TRUE

}


```

```{r Process power path data}
if(file_list_pp_flag){
  for (file in file_list_pp){
  print(file)
  pp_data_raw <- read_excel(path =
                              paste0(user_directory,
                                     "/AP & Cytology Signed Cases Reports/",
                                     file),
                            skip = 1, 1)
  
  pp_data_raw <- data.frame(pp_data_raw[-nrow(pp_data_raw), ],
                            stringsAsFactors = FALSE)
  preprocessed_cyto <- cyto_prep(pp_data_raw)
  key_cols <- c("CASE_NO","SPEC_CODE")
  update_cols <- names(preprocessed_cyto)
  update_cols <- update_cols[! update_cols %in% key_cols]
  if(nrow(preprocessed_cyto)!=0){
      write_temporary_table_to_database_and_merge_updated(preprocessed_cyto,
                                                      key_columns = key_cols,
                                                      update_columns = update_cols,
                                                      source_table_name="LAB_KPI_POWERPATH_CYTO_BIOPSY_ST",
                                                      destination_table_name="LAB_KPI_POWERPATH_CYTO_BIOPSY")
    }
  }

}else{
  print("Powerpath Data up to date")
}

```


```{r Process and Migrate SCC Data}

if(file_list_scc_flag){
  # Process SCC files and push the data to DB -----
  for (file in file_list_scc){
    print(file)
    scc_data <- read_excel(path = paste0(user_directory, "/SCC CP Reports/", file))
    scc_daily_preprocessed <- preprocess_scc(scc_data)
    key_cols <- c("ORDERID","TEST", "RESULTTIME","TESTNAME")
    update_cols <- names(scc_daily_preprocessed)
    update_cols <- update_cols[! update_cols %in% key_cols]
    write_temporary_table_to_database_and_merge_updated(scc_daily_preprocessed,
                                                        key_columns = key_cols,
                                                        update_columns = update_cols,
                                                        source_table_name="LAB_KPI_PREPROCESSED_DAILY_ST",
                                                        destination_table_name="LAB_KPI_PREPROCESSED_DAILY")

  
  }
}else{
  print("SCC Data up to date")
}

```

```{r Process and Migrate SUNQUEST Data}


# Process SUNQUEST files and push the data to DB

if(file_list_sun_flag){

  for (file in file_list_sun){
    print(file)
    sun_data <- read_excel(
      path = paste0(user_directory, "/SUN CP Reports/", file),
      col_types = c("text", "text", "text", "text", "text",
                    "text", "text", "text", "text",
                    "numeric", "numeric", "numeric", "numeric", "numeric",
                    "text", "text", "text", "text", "text",
                    "text", "text", "text", "text", "text",
                    "text", "text", "text", "text", "text",
                    "text", "text", "text", "text", "text", "text"))
    sun_daily_preprocessed <- preprocess_daily_sun(sun_data)
    key_cols <- c("ORDERID","TEST","RESULTTIME", "TESTNAME")
    update_cols <-  names(sun_daily_preprocessed)
    update_cols <- update_cols[! update_cols %in% key_cols]
    write_temporary_table_to_database_and_merge_updated(data =sun_daily_preprocessed,
                                                        key_columns = key_cols,
                                                        update_columns = update_cols,
                                                        source_table_name="LAB_KPI_PREPROCESSED_DAILY_ST",
                                                        destination_table_name="LAB_KPI_PREPROCESSED_DAILY")
  }
}else{
  print("SUN Data up to date")
}
  
```

```{r Check for Missing Days in Database}

dates_check <- NA
if(todays_date-1 > floor_date(todays_date,"month")){
  dates_check <- seq.Date(from = floor_date(todays_date,"month"),
                      to = todays_date-1,
                      by = "day")
}

scc_dates <- glue("SELECT DISTINCT RESULTDATE
                   FROM LAB_KPI_PREPROCESSED_DAILY
                   WHERE SITE IN ('MSH','MSQ','MSUS','MSC') AND
                   RESULTDATE >=  TRUNC(SYSDATE,'mm')
                   ORDER BY RESULTDATE;")

sun_dates <- glue("SELECT DISTINCT RESULTDATE
                   FROM LAB_KPI_PREPROCESSED_DAILY
                   WHERE SITE IN ('MSSN','MSBI','MSM','MSW') AND
                   RESULTDATE >=  TRUNC(SYSDATE,'mm')
                   ORDER BY RESULTDATE;")

pp_dates <- glue("SELECT DISTINCT SIGNED_OUT_DATE
                   FROM LAB_KPI_POWERPATH_CYTO_BIOPSY
                   WHERE SIGNED_OUT_DATE >=  TRUNC(SYSDATE,'mm')
                   ORDER BY SIGNED_OUT_DATE;")

dsn <- "OAO Cloud DB Production"
conn <- dbConnect(odbc(), dsn)
scc_dates_db <- dbGetQuery(conn,
                           scc_dates)
scc_dates_db <- as.Date(scc_dates_db$RESULTDATE)

sun_dates_db <- dbGetQuery(conn,
                           sun_dates)
sun_dates_db <- as.Date(sun_dates_db$RESULTDATE)

pp_dates_db <- dbGetQuery(conn,
                           pp_dates)
pp_dates_db <- as.Date(pp_dates_db$SIGNED_OUT_DATE)


dbDisconnect(conn)


# Check missing dates
missing_scc_dates <- dates_check[!(dates_check %in% scc_dates_db)]
missing_scc_dates_file_dates <- missing_scc_dates+1
missing_sun_dates <- dates_check[!(dates_check %in% sun_dates_db)]
missing_sun_dates_file_dates <- missing_sun_dates+1
missing_pp_dates <- dates_check[!(dates_check %in% pp_dates_db)]
missing_pp_dates_file_dates <- missing_pp_dates+1


# Check for SCC files
if(length(missing_scc_dates_file_dates)>1){
  missing_pattern_scc <- paste0("^(Doc){1}.+",
                                missing_scc_dates_file_dates,
                                ".xlsx")
  
  for (file_name_scc in missing_pattern_scc){
    scc_file <- list.files(
    path = paste0(user_directory, "/SCC CP Reports"),
    pattern = file_name_scc)
    if(identical(scc_file, character(0))){
      print(paste("Missing File",file_name_scc))
    }else{
        print(scc_file)
        scc_data <- read_excel(path = paste0(user_directory, "/SCC CP Reports/", scc_file))
        scc_daily_preprocessed <- preprocess_scc(scc_data)
        key_cols <- c("ORDERID","TEST", "RESULTTIME","TESTNAME")
        update_cols <- names(scc_daily_preprocessed)
        update_cols <- update_cols[! update_cols %in% key_cols]
        write_temporary_table_to_database_and_merge_updated(scc_daily_preprocessed,
                                                            key_columns = key_cols,
                                                            update_columns = update_cols,
                                                            source_table_name="LAB_KPI_PREPROCESSED_DAILY_ST",
                                                            destination_table_name="LAB_KPI_PREPROCESSED_DAILY")
  
    }
  }
  
}else if(length(missing_scc_dates_file_dates)==1){
  
  missing_pattern_scc <- paste0("^(Doc){1}.+",
                                missing_scc_dates_file_dates,
                                ".xlsx")
  
  scc_file <- list.files(
  path = paste0(user_directory, "/SCC CP Reports"),
  pattern = missing_pattern_scc)
  if(identical(scc_file, character(0))){
    print(paste("Missing File",scc_file))
  }else{
      print(scc_file)
      scc_data <- read_excel(path = paste0(user_directory, "/SCC CP Reports/", scc_file))
      scc_daily_preprocessed <- preprocess_scc(scc_data)
      key_cols <- c("ORDERID","TEST", "RESULTTIME","TESTNAME")
      update_cols <- names(scc_daily_preprocessed)
      update_cols <- update_cols[! update_cols %in% key_cols]
      write_temporary_table_to_database_and_merge_updated(scc_daily_preprocessed,
                                                          key_columns = key_cols,
                                                          update_columns = update_cols,
                                                          source_table_name="LAB_KPI_PREPROCESSED_DAILY_ST",
                                                          destination_table_name="LAB_KPI_PREPROCESSED_DAILY")

  }
  

  
}else{
  print("All SCC Result Dates in DB")
}

# Check for SUN files
if(length(missing_sun_dates_file_dates)>1){

  missing_pattern_sun <-  paste0("^(KPI_Daily_TAT_Report){1}.*",
                         missing_sun_dates_file_dates,
                         ".xls")
  
  for (file_name_sun in missing_pattern_sun){
    sun_file <- list.files(
      path = paste0(user_directory, "/SUN CP Reports"),
      pattern = file_name_sun)
    if(identical(sun_file, character(0))){
      print(paste("Missing File",file_name_sun))
    }else{
      print(sun_file)
      sun_data <- read_excel(
        path = paste0(user_directory, "/SUN CP Reports/", sun_file),
        col_types = c("text", "text", "text", "text", "text",
                      "text", "text", "text", "text",
                      "numeric", "numeric", "numeric", "numeric", "numeric",
                      "text", "text", "text", "text", "text",
                      "text", "text", "text", "text", "text",
                      "text", "text", "text", "text", "text",
                      "text", "text", "text", "text", "text", "text"))
      sun_daily_preprocessed <- preprocess_daily_sun(sun_data)
      key_cols <- c("ORDERID","TEST","RESULTTIME", "TESTNAME")
      update_cols <-  names(sun_daily_preprocessed)
      update_cols <- update_cols[! update_cols %in% key_cols]
      write_temporary_table_to_database_and_merge_updated(data =sun_daily_preprocessed,
                                                          key_columns = key_cols,
                                                          update_columns = update_cols,
                                                          source_table_name="LAB_KPI_PREPROCESSED_DAILY_ST",
                                                          destination_table_name="LAB_KPI_PREPROCESSED_DAILY")
  
    }
  }
}else if(length(missing_sun_dates_file_dates)==1){
  
  missing_pattern_sun <-  paste0("^(KPI_Daily_TAT_Report){1}.*",
                         missing_sun_dates_file_dates,
                         ".xls")
  
  sun_file <- list.files(
    path = paste0(user_directory, "/SUN CP Reports"),
    pattern = missing_pattern_sun)
  if(identical(sun_file, character(0))){
    print(paste("Missing File",missing_pattern_sun))
  }else{
    print(sun_file)
    sun_data <- read_excel(
      path = paste0(user_directory, "/SUN CP Reports/", sun_file),
      col_types = c("text", "text", "text", "text", "text",
                    "text", "text", "text", "text",
                    "numeric", "numeric", "numeric", "numeric", "numeric",
                    "text", "text", "text", "text", "text",
                    "text", "text", "text", "text", "text",
                    "text", "text", "text", "text", "text",
                    "text", "text", "text", "text", "text", "text"))
    sun_daily_preprocessed <- preprocess_daily_sun(sun_data)
    key_cols <- c("ORDERID","TEST","RESULTTIME", "TESTNAME")
    update_cols <-  names(sun_daily_preprocessed)
    update_cols <- update_cols[! update_cols %in% key_cols]
    write_temporary_table_to_database_and_merge_updated(data =sun_daily_preprocessed,
                                                        key_columns = key_cols,
                                                        update_columns = update_cols,
                                                        source_table_name="LAB_KPI_PREPROCESSED_DAILY_ST",
                                                        destination_table_name="LAB_KPI_PREPROCESSED_DAILY")
  
    }

  
}else{
  print("All SUN Result Dates in DB")
}


# Check for PP files

```
